### ISSUE TITLE
Are you trying to create something like this?

### ISSUE THREAD

**Issue by georgezim85** [ignatenkovnikita/yii2-digitaldirect-ivr#1]
Do you know this project?
 [zenoracha/voice-elements](https://github.com/zenorocha/voice-elements)

What do you think about to include this library in your project yii2-digitaldirect-ivr ?

I'd like to participate. I would like to create a useful widget that we could use to send commands to Yii2 application using voice.

**Comment by ignatenkovnikita** [comment]
I don't know this project.
This repositoriy only client for api suite digital-direct.ru.
You create a new repository for widget. Best idea, voice commands to Yii2)))

**Comment by georgezim85** [comment]
nice! Thanks!
